const Rewards = Object.freeze([
	{ name: "Battlepoly - Case Départ", image: "battlepoly_start" },
	{ name: "Battlepoly - Case Prison", image: "battlepoly_prison" },
	{ name: "Battlepoly - Caisse de Communauté", image: "battlepoly_community" },
	{ name: "Battlepoly - Électricité", image: "battlepoly_electric" },
	{ name: "Battlepoly - Taxe de Luxe", image: "battlepoly_luxe" },
	{ name: "Battlepoly - Les Eaux", image: "battlepoly_water" },
	{ name: "Battlepoly - Les Gares", image: "battlepoly_gares" },
	{ name: "Battlepoly - Rues Ciel", image: "battlepoly_ciel" },
	{ name: "Battlepoly - Rues Jaunes", image: "battlepoly_jaune" },
	{ name: "Battlepoly - Rues Marines", image: "battlepoly_marine" },
	{ name: "Battlepoly - Rues Oranges", image: "battlepoly_orange" },
	{ name: "Battlepoly - Rues Roses", image: "battlepoly_rose" },
	{ name: "Battlepoly - Rues Rouges", image: "battlepoly_rouge" },
	{ name: "Battlepoly - Rues Vertes", image: "battlepoly_vert" },
	{ name: "Battlepoly - Rues Violettes", image: "battlepoly_violet" },
	{ name: "Battlepoly - Ticket d'Or", image: "battlepoly_gold" },
	{ name: "Carte de Presse", image: "news_presse" },
	{ name: "Carte de Radiotélé", image: "news_radiotv" },
	{ name: "La Campagne d'Egypte", image: "egypte" },
	{ name: "Le Paris Noir", image: "bpw" },
	{ name: "Il a perdu la tête !", image: "stdenis" },
	{ name: "Le Poinçonneur des Lilas", image: "lilas" },
	{ name: "Apéro !%20(événement)", image: "apero" },
	{ name: "Le Noël de Paris (événement)", image: "xmas" },
	{ name: "Le Soldat Inconnu (événement)", image: "soldat_inconnu" },
	{ name: "Les Loups sont Entrés dans Paris", image: "loups" },
	{ name: "Les Morts-Vibrants", image: "zombies" },
	{ name: "Les Enfers à Paris", image: "lenfer" },
	{ name: "Par tous les Saints !", image: "toussaints" },
	{ name: "Space Oddity", image: "spaceinvader01" },
	{ name: "Visiteur de L'Origine", image: "scout_origine" },
	{ name: "Visiteur de Seine", image: "scout_vaux" },
	{ name: "Visiteur des Alentours", image: "scout_banlieue" },
	{ name: "Visiteur des Monts", image: "scout_monts" },
	{ name: "Visiteur entre les Murs", image: "scout_total" },
	{ name: "Mercure", image: "mercure_silver" },
	{ name: "Hermès", image: "mercure_gold" },
	{ name: "Super Touriste", image: "tourist01" },
	{ name: "Mini-Pouce", image: "pouce01" },
	{ name: "Band on the Run", image: "concert01" },
	{ name: "Bon Voyage !", image: "plane01" },
	{ name: "Exposition Paris 1878", image: "expo1878" },
	{ name: "Exposition Paris 1900", image: "expo1900" },
	{ name: "Exposition Paris 1937", image: "expo1937" },
	{ name: "Exposition Trans-temporelle", image: "expo_all" },
	{ name: "Jeux Olympiques 1900", image: "jo1900" },
	{ name: "Jeux Olympiques 1924", image: "jo1924" },
	{ name: "Jeux Olympiques 2024", image: "jo2024" },
	{ name: "Jeux Olympiques Transtemporels", image: "jo_all" },
	{ name: "Grand-Maire", image: "mairie01" },
	{ name: "0.%20La%20République", image: "pouvoir04" },
	{ name: "1.%20Bleu :%20Le%20Pouvoir%20Exécutif", image: "pouvoir01" },
	{ name: "3.%20Rouge%20:%20Le%20pouvoir%20Judiciaire", image: "pouvoir03" },
	{ name: "Allô Maman bobo", image: "allobobo01" },
	{ name: "La Vie de Château", image: "chateau01" },
	{ name: "Les Châteaux Fantômes", image: "ghost01" },
	{ name: "La Commune de Paris", image: "commune01" },
	{ name: "Culture & Confiture", image: "musee01" },
	{ name: "Universitas", image: "universitas01" },
	{ name: "Super Meufs", image: "supermeufs01" },
	{ name: "L'effort Deux-tiers", image: "forts01" },
	{ name: "Il va y avoir du sport !", image: "sport01" },
    { name: "Les Petits Chevaux", image: "hippodrome01" },
    { name: "Les Petits Coureurs", image: "velo01" },
	{ name: "Les Petits Canards", image: "loisirs01" },
	{ name: "Auprès de mon Arbre", image: "jardins01" },
	{ name: "Les Cîmes", image: "cimes01" },	
	{ name: "Les Indie Loses", image: "indielose01" },
	{ name: "Ils Sont Fous Ces Romains !", image: "romains" },
	{ name: "Le Train Fantôme", image: "ghoststation" },
	{ name: "La Petite Ceinture", image: "petiteceinture01" },
	{ name: "La Grande Ceinture", image: "grandeceinture01" },
	{ name: "Vétéran du Funiculaire de Montmartre", image: "funiculaire01" },
	{ name: "Vétéran du Métro 1", image: "line01_01" },
	{ name: "Vétéran du Métro 2", image: "line02_01" },
	{ name: "Vétéran du Métro 3", image: "line03_01" },
	{ name: "Vétéran du Métro 3bis", image: "line03bis_01" },
	{ name: "Vétéran du Métro 4", image: "line04_01" },
	{ name: "Vétéran du Métro 5", image: "line05_01" },
	{ name: "Vétéran du Métro 6", image: "line06_01" },
	{ name: "Vétéran du Métro 7", image: "line07_01" },
	{ name: "Vétéran du Métro 7bis", image: "line07bis_01" },
	{ name: "Vétéran du Métro 8", image: "line08_01" },
	{ name: "Vétéran du Métro 9", image: "line09_01" },
	{ name: "Vétéran du Métro 10", image: "line10_01" },
	{ name: "Vétéran du Métro 11", image: "line11_01" },
	{ name: "Vétéran du Métro 12", image: "line12_01" },
	{ name: "Vétéran du Métro 13", image: "line13_01" },
	{ name: "Vétéran du Métro 14", image: "line14_01" },
	{ name: "Vétéran du RER A", image: "lineA_01" },
	{ name: "Vétéran du RER B", image: "lineB_01" },
	{ name: "Vétéran du RER C", image: "lineC_01" },
	{ name: "Vétéran du RER D", image: "lineD_01" },
	{ name: "Vétéran du RER E", image: "lineE_01" },
	{ name: "Vétéran du Tram T1", image: "lineT1_01" },
	{ name: "Vétéran du Tram T2", image: "lineT2_01" },
	{ name: "Vétéran du Tram T3a", image: "lineT3a_01" },
	{ name: "Vétéran du Tram T3b", image: "lineT3b_01" },
	{ name: "Vétéran du Tram T4", image: "lineT4_01" },
	{ name: "Vétéran du Tram T5", image: "lineT5_01" },
	{ name: "Vétéran du Tram T6", image: "lineT6_01" },
	{ name: "Vétéran du Tram T7", image: "lineT7_01" },
	{ name: "Vétéran du Tram T8", image: "lineT8_01" },
	{ name: "Vétéran du Tram T11", image: "lineT11_01" },
	{ name: "Vétéran du Transilien H", image: "lineH_01" },
	{ name: "Vétéran du Transilien J", image: "lineJ_01" },
	{ name: "Vétéran du Transilien K", image: "lineK_01" },
	{ name: "Vétéran du Transilien L", image: "lineL_01" },
	{ name: "Vétéran du Transilien N", image: "lineN_01" },
	{ name: "Vétéran du Transilien P", image: "lineP_01" },
	{ name: "Vétéran du Transilien R", image: "lineR_01" }
]);
